export const reports = [
  {
      "id": 1,
      "date": "2023-09-02",
      "time": "21:44",
      "location": "Corridor",
      "type": ["Verbal Abuse"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "The guy has a long hair but not too long, he is tall but not too tall and has a beard. He was wearing a black shirt and blue jeans.",
      "severity": 5,
      "additionalInfo": "Additional information about the complaint.",
      "status": "resolved"
  },
  {
      "id": 2,
      "date": "2023-01-03",
      "time": "11:14",
      "location": "Sports Ground",
      "type": ["Verbal Abuse"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 9,
      "additionalInfo": "Additional information about the complaint.",
      "status": "resolved"
  },
  {
      "id": 3,
      "date": "2023-03-19",
      "time": "15:02",
      "location": "Classroom",
      "type": ["Verbal Abuse"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 4,
      "additionalInfo": "",
      "status": "under investigation"
  },
  {
      "id": 4,
      "date": "2023-10-29",
      "time": "00:34",
      "location": "Corridor",
      "type": ["Verbal Abuse"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 1,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 5,
      "date": "2023-10-24",
      "time": "02:44",
      "location": "Corridor",
      "type": ["Verbal Abuse"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 7,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 6,
      "date": "2023-01-09",
      "time": "19:21",
      "location": "Corridor",
      "type": ["Verbal Abuse", "Sexual Harassesment", "Bullying", "Stalking", "Cyber Harassment", "Physical Harassment"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 10,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 7,
      "date": "2023-04-10",
      "time": "20:29",
      "location": "Corridor",
      "type": ["Stalking"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 3,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 8,
      "date": "2023-01-11",
      "time": "08:31",
      "location": "Library",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 4,
      "additionalInfo": "",
      "status": "under investigation"
  },
  {
      "id": 9,
      "date": "2023-07-05",
      "time": "13:03",
      "location": "Library",
      "type": ["Verbal Abuse"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 6,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 10,
      "date": "2023-10-16",
      "time": "17:24",
      "location": "Library",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 9,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 11,
      "date": "2023-12-07",
      "time": "19:32",
      "location": "Classroom",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 7,
      "additionalInfo": "Additional information about the complaint.",
      "status": "unreviewed"
  },
  {
      "id": 12,
      "date": "2023-12-16",
      "time": "16:34",
      "location": "Parking Lot",
      "type": ["Sexual Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 9,
      "additionalInfo": "Additional information about the complaint.",
      "status": "unreviewed"
  },
  {
      "id": 13,
      "date": "2023-10-31",
      "time": "21:52",
      "location": "Corridor",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 4,
      "additionalInfo": "Additional information about the complaint.",
      "status": "resolved"
  },
  {
      "id": 14,
      "date": "2023-11-24",
      "time": "15:11",
      "location": "Corridor",
      "type": ["Stalking"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 8,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 15,
      "date": "2023-01-22",
      "time": "17:44",
      "location": "Classroom",
      "type": ["Sexual Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 3,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 16,
      "date": "2023-12-24",
      "time": "06:10",
      "location": "Corridor",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 8,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 17,
      "date": "2023-01-26",
      "time": "14:09",
      "location": "Cafeteria",
      "type": ["Cyber Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 10,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 18,
      "date": "2023-09-17",
      "time": "05:32",
      "location": "Corridor",
      "type": ["Physical Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 6,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 19,
      "date": "2023-02-27",
      "time": "08:07",
      "location": "Classroom",
      "type": ["Verbal Abuse"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 10,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 20,
      "date": "2023-08-08",
      "time": "08:04",
      "location": "Parking Lot",
      "type": ["Physical Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 1,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 21,
      "date": "2023-09-24",
      "time": "17:30",
      "location": "Cafeteria",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 8,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 22,
      "date": "2023-07-18",
      "time": "16:44",
      "location": "Parking Lot",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 10,
      "additionalInfo": "Additional information about the complaint.",
      "status": "unreviewed"
  },
  {
      "id": 23,
      "date": "2023-04-08",
      "time": "18:41",
      "location": "Sports Ground",
      "type": ["Verbal Abuse"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 2,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 24,
      "date": "2023-04-06",
      "time": "07:17",
      "location": "Classroom",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 5,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 25,
      "date": "2023-12-13",
      "time": "22:11",
      "location": "Sports Ground",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 7,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 26,
      "date": "2023-03-17",
      "time": "14:41",
      "location": "Cafeteria",
      "type": ["Physical Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 6,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 27,
      "date": "2023-08-20",
      "time": "12:45",
      "location": "Classroom",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 6,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 28,
      "date": "2023-04-02",
      "time": "09:57",
      "location": "Sports Ground",
      "type": ["Physical Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 4,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 29,
      "date": "2023-12-22",
      "time": "21:07",
      "location": "Corridor",
      "type": ["Stalking"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 1,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 30,
      "date": "2023-11-26",
      "time": "15:35",
      "location": "Parking Lot",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 7,
      "additionalInfo": "Additional information about the complaint.",
      "status": "unreviewed"
  },
  {
      "id": 31,
      "date": "2023-07-30",
      "time": "19:35",
      "location": "Library",
      "type": ["Stalking"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 7,
      "additionalInfo": "Additional information about the complaint.",
      "status": "unreviewed"
  },
  {
      "id": 32,
      "date": "2023-01-08",
      "time": "23:44",
      "location": "Classroom",
      "type": ["Stalking"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 6,
      "additionalInfo": "Additional information about the complaint.",
      "status": "unreviewed"
  },
  {
      "id": 33,
      "date": "2023-07-15",
      "time": "01:29",
      "location": "Sports Ground",
      "type": ["Sexual Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 4,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 34,
      "date": "2023-12-19",
      "time": "16:19",
      "location": "Library",
      "type": ["Physical Harassment"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 7,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 35,
      "date": "2023-08-11",
      "time": "03:21",
      "location": "Cafeteria",
      "type": ["Stalking"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 5,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 36,
      "date": "2023-10-30",
      "time": "23:23",
      "location": "Cafeteria",
      "type": ["Physical Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 10,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 37,
      "date": "2023-08-20",
      "time": "08:07",
      "location": "Corridor",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 7,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 38,
      "date": "2023-05-08",
      "time": "16:25",
      "location": "Corridor",
      "type": ["Cyber Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 10,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 39,
      "date": "2023-05-04",
      "time": "21:44",
      "location": "Classroom",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 1,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 40,
      "date": "2023-03-13",
      "time": "05:54",
      "location": "Classroom",
      "type": ["Stalking"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 2,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 41,
      "date": "2023-06-26",
      "time": "16:56",
      "location": "Sports Ground",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 7,
      "additionalInfo": "",
      "status": "under investigation"
  },
  {
      "id": 42,
      "date": "2023-09-02",
      "time": "23:14",
      "location": "Parking Lot",
      "type": ["Physical Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 10,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 43,
      "date": "2023-12-06",
      "time": "07:06",
      "location": "Cafeteria",
      "type": ["Cyber Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 1,
      "additionalInfo": "Additional information about the complaint.",
      "status": "unreviewed"
  },
  {
      "id": 44,
      "date": "2023-02-20",
      "time": "23:53",
      "location": "Classroom",
      "type": ["Physical Harassment"],
      "isAnonymous": true,
      "hasEvidence": true,
      "harasserDetails": "",
      "severity": 4,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 45,
      "date": "2023-01-17",
      "time": "14:10",
      "location": "Cafeteria",
      "type": ["Sexual Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 8,
      "additionalInfo": "",
      "status": "under investigation"
  },
  {
      "id": 46,
      "date": "2023-08-18",
      "time": "03:41",
      "location": "Cafeteria",
      "type": ["Verbal Abuse"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 1,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 47,
      "date": "2023-03-29",
      "time": "18:12",
      "location": "Cafeteria",
      "type": ["Cyber Harassment"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "",
      "severity": 5,
      "additionalInfo": "",
      "status": "unreviewed"
  },
  {
      "id": 48,
      "date": "2023-11-11",
      "time": "16:37",
      "location": "Parking Lot",
      "type": ["Cyber Harassment"],
      "isAnonymous": false,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 4,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  },
  {
      "id": 49,
      "date": "2023-02-16",
      "time": "00:38",
      "location": "Parking Lot",
      "type": ["Sexual Harassment"],
      "isAnonymous": false,
      "hasEvidence": true,
      "harasserDetails": "Details about the harasser",
      "severity": 2,
      "additionalInfo": "",
      "status": "resolved"
  },
  {
      "id": 50,
      "date": "2023-01-20",
      "time": "16:58",
      "location": "Classroom",
      "type": ["Cyber Harassment"],
      "isAnonymous": true,
      "hasEvidence": false,
      "harasserDetails": "Details about the harasser",
      "severity": 10,
      "additionalInfo": "Additional information about the complaint.",
      "status": "under investigation"
  }
]